name: notebooks
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy = 1.21.5
  - matplotlib = 3.5.1
  - ipywidgets
  - scipy = 1.7.3
  - numba = 0.55.1
  - pip
  - pip:
  - jupyter
    - safepython == 0.1.1
